<center><h1>1강 행렬과 행렬식</h1></center>
<hr>

## Table of Contents <a id="top"></a>

1. [행렬](#1)
    1. [용어정리](#1.1)
    2. [행렬의 연산](#1.2)
2. [연립일차방정식](#2)
    1. [행렬의 표현](#2.1)
    2. [가우스 조던 소거법](#2.2)
    3. [역행렬 이용](#2.3)
3. [행렬식](#3)
    1. [행렬식이란?](#3.1)
    2. [역행렬](#3.2)
    3. [크래머 공식](#3.3)

<hr>

In [1]:
import numpy as np

# 1. 행렬 <a id="1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 1.1. 용어정리 <a id="1.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 구성

* 성분(component): 행렬 안에 배열된 구성원
* 행(row): 행렬의 가로줄
* 열(column): 행렬의 세로줄
* mxn 행렬: m 행과 n 열로 이루어진 행렬

<img src="./figure/행렬 용어 정리.png"/>

### 주요 행렬

* 대각 행렬(Diagonal Matrix): 대각성분(Diagonal Component)를 제외한 나머지 성분이 0인 행렬.
* 영행렬(Zero Matrix): 모든 성분이 0인 행렬
* 전치 행렬(Transpose Matrix): 주대각선을 기준으로 뒤집은 행렬. a(i, j)가 a(j, i)로 변한다.
* 대칭 행렬(Symmetric Matrix): 행렬 A와 전치 행렬 AT가 같은 행렬 A
* 정사각 행렬(Square Matrix): 행과 열의 개수가 같은 행렬
* 단위 행렬(Identity Matrix): 모든 대각성분이 1이고 나머지 성분은 0인 정사각 행렬

In [2]:
diagonal_matrix = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0]])
print('대각 행렬>>\n{}'.format(diagonal_matrix))

대각 행렬>>
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [3]:
zero_matrix = np.zeros((3, 2), dtype=int)
print('대각 행렬>>\n{}'.format(zero_matrix))

대각 행렬>>
[[0 0]
 [0 0]
 [0 0]]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_transpose = a.T
print('원래 행렬>>\n{}\n'.format(a))
print('전치 행렬>>\n{}'.format(a_transpose))

원래 행렬>>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

전치 행렬>>
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [5]:
symmetric_matrix = np.array([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print('대칭 행렬>>\n{}\n'.format(symmetric_matrix))
print('전치된 대칭 행렬>>\n{}'.format(symmetric_matrix.T))

대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]

전치된 대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]


In [6]:
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('정사각 행렬>>\n{}'.format(square_matrix))

정사각 행렬>>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
identity_matrix_2x2 = np.eye(2, dtype=int)
print('2x2 단위 행렬>>\n{}\n'.format(identity_matrix_2x2))

identity_matrix_3x3 = np.eye(3, dtype=int)
print('3x3 단위 행렬>>\n{}'.format(identity_matrix_3x3))

2x2 단위 행렬>>
[[1 0]
 [0 1]]

3x3 단위 행렬>>
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 1.2. 행렬의 연산 <a id="1.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 덧셈, 뺄셈, 상수배

* 덧셈, 뺄셈, 상수배 연산은 같은 위치에 행렬의 성분끼리 연산한다.
* 덧셈에 대해서는 교환법칙(A + B = B + A)와 결합법칙(A + (B + C) = (A + B) + C) 모두 성립한다

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[1 1 1]
 [2 2 2]]


In [9]:
a_add_b = a + b
b_add_a = b + a
print('A + B>>\n{}\n'.format(a_add_b))
print('B + A>>\n{}'.format(b_add_a))

A + B>>
[[2 3 4]
 [6 7 8]]

B + A>>
[[2 3 4]
 [6 7 8]]


In [10]:
a_sub_b = a - b
b_sub_a = b - a
print('A - B>>\n{}\n'.format(a_sub_b))
print('B - A>>\n{}'.format(b_sub_a))

A - B>>
[[0 1 2]
 [2 3 4]]

B - A>>
[[ 0 -1 -2]
 [-2 -3 -4]]


In [11]:
scalar = 3
a_increase_c = a * scalar
c_increase_a = scalar * a
print('A x {}>>\n{}\n'.format(scalar, a_increase_c))
print('{} x A>>\n{}'.format(scalar, c_increase_a))

A x 3>>
[[ 3  6  9]
 [12 15 18]]

3 x A>>
[[ 3  6  9]
 [12 15 18]]


### 행렬의 곱셈

* 행렬의 곱셈 AB를 위해서는 A의 열의 개수와 B의 행의 개수가 같아야한다. 연산의 결과로 A의 행의 개수 x B의 열의 개수 크기의 행렬이 나온다
* 행렬의 곱셈은 교환법칙이 성립하지 않는다. 대신 결합법칙은 성립한다. 따라서 분배법칙도 가능하다

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

3x2 행렬 B>>
[[1 1]
 [2 2]
 [3 3]]


In [13]:
a_dot_b = a @ b
b_dot_a = b @ a
print('AB>>\n{}\n'.format(a_dot_b))
print('BA>>\n{}'.format(b_dot_a))

AB>>
[[14 14]
 [32 32]]

BA>>
[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}\n'.format(b.shape[0], b.shape[1], b))
print('{}x{} 행렬 C>>\n{}'.format(c.shape[0], c.shape[1], c))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[ 7  8  9]
 [10 11 12]]

3x2 행렬 C>>
[[1 1]
 [2 2]
 [3 3]]


In [15]:
a_dot_c_add_b_dot_c = (a @ c) + (b @ c)
a_add_b_dot_c = (a + b) @ c
print('AC + BC>>\n{}\n'.format(a_dot_c_add_b_dot_c))
print('(A + B)C>>\n{}'.format(a_add_b_dot_c))

AC + BC>>
[[ 64  64]
 [100 100]]

(A + B)C>>
[[ 64  64]
 [100 100]]


### 행렬의 곱셈 = 함수의 합성

<img src="./figure/행렬 곱셈 합성.png"/>

# 2. 연립일차방정식 <a id="2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 2.1. 행렬의 표현 <a id="2.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬과 연립일차방정식

* 행렬은 연립일차방정식의 해를 구하기 위해서 등장
* 연립일차방정식의 해를 구하는데 있어서 행렬을 사용하는 방법으로 (1) <b>가우스 조던 방법</b>과 (2) <b>역행렬</b>이 있다


<img src="./figure/연립일차방정식 표현.png"/>

## 2.2. 가우스 조던 소거법 <a id="2.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 가우스 조던 소거법

* 세 가지 기본행 연산을 사용해서 첨가행렬을 기약 행 사다리꼴로 변환하여 해를 구한다
    1. 한 행을 상수배한다
    2. 한 행을 상수배하여서 다른 행에 더한다
    3. 두 행을 맞바꾼다
* 가우스 소거법은 행 사다리꼴로 변환하는 과정을, 가우스 조던 소거법은 기약 행 사다리꼴로 변환하는 과정을 의미한다.
    * 행 사다리꼴은 각 행의 가장 왼쪽 1을 기준으로 다음 행의 값이 모두 0인 사다리꼴 형태
    * 기약 행 사다리꼴은 각 행의 가장 왼쪽 1을 기준으로 이전과 다음 행의 값이 모두 0인 사다리꼴 형태
* 가우스 소거법으로 해를 구하는 경우 상수해(해가 1개), 부정(해가 여러개, 일반해), 불능(해가 없음)이 나올 수 있다
* 가우스 조던 소거법은 효율적인 알고리즘은 아니지만 프로그래밍으로 알고리즘화 할 수 있으며 나아가 다양한 수학 원리의 기본이라는 점에서 중요하다

<img src="./figure/가우스 조던 소거법.png"/>

In [32]:
def swap(mat, i, j):
    mat[[i, j]] = mat[[j, i]]

In [165]:
def gauss_jordan(mat, jordan=True):
    n_row = mat.shape[0]
    n_col = mat.shape[1]
    
    row = 0
    col = 0 # index of col, which must be non-zero

    # 가우스 소거법
    while row < n_row:
        # 만약 행의 시작이 0이라면 다음 행과 swap
        if row + 1 < n_row and mat[row, col] == 0:
            swap(mat, row, row + 1)
            col += 1
        else:
            # 0이 아닌 값을 찾자!!!
            value = mat[row, col]
            if col + 1 < n_col and value == 0:
                col += 1
                value = mat[row, col]
            
            # 혹시 0으로 나누는 문제를 대비해서...
            if value != 0:
                mat[row] = mat[row] / value
            
            # -0이 보기 싫으니깐. 0으로 통일하자
            mat[row, :col] = 0
            
            # 현재 행의 시작은 1로 설정되었다. 이제부터 다음 행에서는 모두 값이 0이 되도록 소거한다
            for idx in range(row + 1, n_row):
                mat[idx] = mat[idx] - mat[row] * (mat[idx, col] / mat[row, col])
            
            row += 1
    
    # 조단 소거법
    if jordan:
        row = n_row - 1
        col = n_col - 2
        
        while row > 0:
            # 만약 현재 col이 0이라면 그건 해당 row가 모두 0이라는 것
            if mat[row, col] == 0:
                row -= 1
                continue

            # 만약 col이 1이 아니라면 일단 이전으로 이동한다. 가우스 조단 소거법에 의해서 일다 1로 시작해야한다.
            if col - 1 > 0 and mat[row, col] != 1:
                col -= 1

            # 1로 시작하는 경우에 대해서 소거법으로 위의 행들을 처리한다
            for idx in range(0, row):
                mat[idx] = mat[idx] - mat[row] * mat[idx, col]
            
            row -= 1
            col -= 1

In [166]:
original = np.array([[1, 2, 5], [2, 3, 8]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[1. 2. 5.]
 [2. 3. 8.]]

가우스 소거법 행렬 >>
[[1. 2. 5.]
 [0. 1. 2.]]

가우스 조던 소거법 행렬 >>
[[1. 0. 1.]
 [0. 1. 2.]]


In [167]:
original = np.array([[2, 4, -3, 1], [1, 1, 2, 9], [3, 6, -5, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))


원 행렬 >>
[[ 2.  4. -3.  1.]
 [ 1.  1.  2.  9.]
 [ 3.  6. -5.  0.]]

가우스 소거법 행렬 >>
[[ 1.          2.         -1.5         0.5       ]
 [ 0.          0.          1.          2.42857143]
 [ 0.          0.          0.          1.        ]]

가우스 조던 소거법 행렬 >>
[[1.         2.         0.         4.14285714]
 [0.         0.         1.         2.42857143]
 [0.         0.         0.         1.        ]]


In [168]:
original = np.array([[1, -1, 2, 5], [2, -3, 1, -10], [3, -3, 6, 15]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[  1.  -1.   2.   5.]
 [  2.  -3.   1. -10.]
 [  3.  -3.   6.  15.]]

가우스 소거법 행렬 >>
[[ 1.         -1.          2.          5.        ]
 [ 0.          0.          1.          6.66666667]
 [ 0.          0.          0.          0.        ]]

가우스 조던 소거법 행렬 >>
[[ 1.         -1.          0.         -8.33333333]
 [ 0.          0.          1.          6.66666667]
 [ 0.          0.          0.          0.        ]]


In [169]:
original = np.array([[2, 4, -2, 6], [1, 1, 2, 9], [1, 2, -1, 4]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 2.  4. -2.  6.]
 [ 1.  1.  2.  9.]
 [ 1.  2. -1.  4.]]

가우스 소거법 행렬 >>
[[ 1.  2. -1.  3.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  1.]]

가우스 조던 소거법 행렬 >>
[[1. 2. 0. 5.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]


In [170]:
original = np.array([[1, 1, 2, 4, 1, 0], [0, 0, 1, 1, 2, 0], [2, 2, -1, 0, 3, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 1.  1.  2.  4.  1.  0.]
 [ 0.  0.  1.  1.  2.  0.]
 [ 2.  2. -1.  0.  3.  0.]]

가우스 소거법 행렬 >>
[[ 1.          1.          2.          4.          1.          0.        ]
 [ 0.          0.          1.          1.          2.          0.        ]
 [ 0.          0.          0.          1.         -3.66666667 -0.        ]]

가우스 조던 소거법 행렬 >>
[[ 1.          1.          0.          0.          4.33333333  0.        ]
 [ 0.          0.          1.          0.          5.66666667  0.        ]
 [ 0.          0.          0.          1.         -3.66666667 -0.        ]]


## 2.3. 역행렬 이용<a id="2.3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 역행렬을 이용한 연립일차방정식 해 구하기

* AX = B에 대해서 행렬 A의 역행렬이 존재할 때 X = A(-1)B이다.
* 역행렬의 존재를 어떻게 판별할지, 그리고 역행렬을 어떻게 구할지가 중요 -> 행렬식

# 3. 행렬식 <a id="3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 3.1. 행렬식이란? <a id="3.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬식(Determinant)

* 행렬식은 정사각 행렬(Square Matrix)를 하나의 수로 대응시키는 특별한 함수를 의미한다.

<img src="./figure/행렬식 공식.png"></img>

* 3x3에서 a11, a12, a13에 대해서 계산하였지만, 같은 행 또는 같은 열의 성분들은 행렬식 계산에 사용할 수 있다.
* 이 때 부호를 주의해야한다.

<img src="./figure/3차 행렬식 구하기.png"/>

### 사루스 법칙(전개) - 3차 행렬식을 빠르게 구하기

* 3차 행렬식을 빠르게 구하기 위한 방법
* 1열과 2열의 값을 행렬 A 오른쪽으로 쌓는다.
* 3차 행렬식은 하향하는 대각선 방향의 성분 곱의 합과 상향하는 대각선 방향의 성분 곱의 합의 차이다

<img src="./figure/사루스 전개.png"/>

In [229]:
def minor_matrix(matrix, i, j):
    minor_matrix = matrix.copy()
    minor_matrix = np.delete(minor_matrix, [i], axis=0)
    minor_matrix = np.delete(minor_matrix, [j], axis=1)
    return minor_matrix

In [230]:
def calculate_determinant(square_matrix, n):
    if n == 0:
        return 0
    if n == 1:
        return square_matrix[0][0]
    
    det = 0.
    for idx in range(n):
        minor_mat = minor_matrix(square_matrix, 0, idx)
        det += (((-1) ** (idx)) * square_matrix[0, idx]) * calculate_determinant(minor_mat, n - 1)
    
    return det

In [232]:
a = np.array([[1, 2, 3], [0, 1, 0], [1, 2, 0]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[1 2 3]
 [0 1 0]
 [1 2 0]]

행렬식 det(A)의 값은 -3.0


In [233]:
a = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[1 2 3]
 [2 5 3]
 [1 0 8]]

행렬식 det(A)의 값은 -1.0


In [234]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 2  4 -3]
 [ 1  1  2]
 [ 3  6 -5]]

행렬식 det(A)의 값은 1.0


In [235]:
a = np.array([[1, -1, 2], [2, -3, 1], [3, -3, 6]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 1 -1  2]
 [ 2 -3  1]
 [ 3 -3  6]]

행렬식 det(A)의 값은 0.0


In [236]:
a = np.array([[2, 4, -2], [1, 1, 2], [1, 2, -1]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 2  4 -2]
 [ 1  1  2]
 [ 1  2 -1]]

행렬식 det(A)의 값은 0.0


In [237]:
a = np.array([[1, 1, 2, 4, 1], [0, 0, 1, 1, 2], [2, 2, -1, 3, 0,], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

5차 행렬 A >> 
[[ 1  1  2  4  1]
 [ 0  0  1  1  2]
 [ 2  2 -1  3  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

행렬식 det(A)의 값은 0.0


## 3.2. 역행렬 <a id="3.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬식과 역행렬

* 행렬 A에 대해서 행렬식 det(A)가 0이면 행렬 A에 대해서 역행렬이 존재하지 않는다. -> 연립일차방정식의 해는 부정 또는 불능
* 행렬 A에 대해서 행렬식 det(A)가 0이 아니면 역행렬 A(-1)는 행렬식과 Minor Matrix의 행렬식을 사용해서 표현한다

<img src="./figure/역행렬 구하기.png"/>

In [263]:
def adjoint_matrix(matrix):
    adj_matrix = np.zeros_like(matrix, dtype=float)
    
    n = matrix.shape[0]
    
    for row in range(n):
        for col in range(n):
            m = minor_matrix(matrix, row, col)
            adj_matrix[col, row] = ((-1) ** (row + col)) * calculate_determinant(m, m.shape[0])
    
    return adj_matrix
    

In [264]:
def calculate_inverse_matrix(matrix):
    det = calculate_determinant(matrix, matrix.shape[0])
    if det != 0:
        adj_matrix = adjoint_matrix(matrix)
        adj_matrix /= det
        return True, adj_matrix
    
    return False, det_matrix

In [265]:
a = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


In [266]:
a = np.array([[2, 1], [4, 3]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[ 1.5 -0.5]
 [-2.   1. ]]


In [267]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[-17.   2.  11.]
 [ 11.  -1.  -7.]
 [  3.  -0.  -2.]]


In [268]:
a_inv @ np.array([1, 9, 0])

array([1., 2., 3.])

## 3.3. 크래머 공식 <a id="3.3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 크래머 공식

* 연립일차방정식의 모든 미지수(x, y, z, ...)를 역행렬을 통해 계산하는 긋은 많은 계산량이 필요하다
* 크래머 공식은 특정한 미지수(x)에 대해서만 그 해를 구할 때 사용하는 방법으로 행렬식을 활용한다

<img src="./figure/크래머 공식.png"/>

In [290]:
def cramer_matrix(matrix, k, constant):
    cramer = matrix.copy()
    cramer[:, k] = constant
    return cramer

In [291]:
def cramer_rule(matrix, constant):
    n = matrix.shape[0]
    variables = list()
    for variable in range(n):
        det_a = calculate_determinant(matrix, matrix.shape[0])
        
        ak = cramer_matrix(matrix, variable, constant)
        det_ak = calculate_determinant(ak, ak.shape[0])
        
        variables.append(det_ak / det_a)
    
    return variables

In [293]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
constant = np.array([1, 9, 0])
print('연립일차방정식을 행렬로 표현한 A >>\n{}\n'.format(a))
print('연립일차방정식의 상수 >> {}\n'.format(constant))
variables = cramer_rule(a, constant)
print('연립일차장정식의 해 >> {}\n'.format(variables))

연립일차방정식을 행렬로 표현한 A >>
[[ 2  4 -3]
 [ 1  1  2]
 [ 3  6 -5]]

연립일차방정식의 상수 >> [1 9 0]

연립일차장정식의 해 >> [1.0, 2.0, 3.0]

