<center><h1>1강 행렬과 행렬식</h1></center>
<hr>

## Table of Contents <a id="top"></a>

1. [행렬](#1)
    1. [용어정리](#1.1)
    2. [행렬의 연산](#1.2)
2. 연립일차방정식
    1. 행렬의 표현
    2. 가우스 조던 소거법
    3. 역행렬 이용
3. 행렬식
    1. 행렬식이란?
    2. 역행렬
    3. 크래머 공식

<hr>

In [1]:
import numpy as np

# 1. 행렬 <a id="1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 1.1. 용어정리 <a id="1.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 구성

* 성분(component): 행렬 안에 배열된 구성원
* 행(row): 행렬의 가로줄
* 열(column): 행렬의 세로줄
* mxn 행렬: m 행과 n 열로 이루어진 행렬

<img src="./figure/행렬 용어 정리.png"/>

### 주요 행렬

* 대각 행렬(Diagonal Matrix): 대각성분(Diagonal Component)를 제외한 나머지 성분이 0인 행렬.
* 영행렬(Zero Matrix): 모든 성분이 0인 행렬
* 전치 행렬(Transpose Matrix): 주대각선을 기준으로 뒤집은 행렬. a(i, j)가 a(j, i)로 변한다.
* 대칭 행렬(Symmetric Matrix): 행렬 A와 전치 행렬 AT가 같은 행렬 A
* 정사각 행렬(Square Matrix): 행과 열의 개수가 같은 행렬
* 단위 행렬(Identity Matrix): 모든 대각성분이 1이고 나머지 성분은 0인 정사각 행렬

In [2]:
diagonal_matrix = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0]])
print('대각 행렬>>\n{}'.format(diagonal_matrix))

대각 행렬>>
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [3]:
zero_matrix = np.zeros((3, 2), dtype=int)
print('대각 행렬>>\n{}'.format(zero_matrix))

대각 행렬>>
[[0 0]
 [0 0]
 [0 0]]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_transpose = a.T
print('원래 행렬>>\n{}\n'.format(a))
print('전치 행렬>>\n{}'.format(a_transpose))

원래 행렬>>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

전치 행렬>>
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [5]:
symmetric_matrix = np.array([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print('대칭 행렬>>\n{}\n'.format(symmetric_matrix))
print('전치된 대칭 행렬>>\n{}'.format(symmetric_matrix.T))

대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]

전치된 대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]


In [6]:
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('정사각 행렬>>\n{}'.format(square_matrix))

정사각 행렬>>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
identity_matrix_2x2 = np.eye(2, dtype=int)
print('2x2 단위 행렬>>\n{}\n'.format(identity_matrix_2x2))

identity_matrix_3x3 = np.eye(3, dtype=int)
print('3x3 단위 행렬>>\n{}'.format(identity_matrix_3x3))

2x2 단위 행렬>>
[[1 0]
 [0 1]]

3x3 단위 행렬>>
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 1.2. 행렬의 연산 <a id="1.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 덧셈, 뺄셈, 상수배

* 덧셈, 뺄셈, 상수배 연산은 같은 위치에 행렬의 성분끼리 연산한다.
* 덧셈에 대해서는 교환법칙(A + B = B + A)와 결합법칙(A + (B + C) = (A + B) + C) 모두 성립한다

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[1 1 1]
 [2 2 2]]


In [9]:
a_add_b = a + b
b_add_a = b + a
print('A + B>>\n{}\n'.format(a_add_b))
print('B + A>>\n{}'.format(b_add_a))

A + B>>
[[2 3 4]
 [6 7 8]]

B + A>>
[[2 3 4]
 [6 7 8]]


In [10]:
a_sub_b = a - b
b_sub_a = b - a
print('A - B>>\n{}\n'.format(a_sub_b))
print('B - A>>\n{}'.format(b_sub_a))

A - B>>
[[0 1 2]
 [2 3 4]]

B - A>>
[[ 0 -1 -2]
 [-2 -3 -4]]


In [11]:
scalar = 3
a_increase_c = a * scalar
c_increase_a = scalar * a
print('A x {}>>\n{}\n'.format(scalar, a_increase_c))
print('{} x A>>\n{}'.format(scalar, c_increase_a))

A x 3>>
[[ 3  6  9]
 [12 15 18]]

3 x A>>
[[ 3  6  9]
 [12 15 18]]


### 행렬의 곱셈

* 행렬의 곱셈 AB를 위해서는 A의 열의 개수와 B의 행의 개수가 같아야한다. 연산의 결과로 A의 행의 개수 x B의 열의 개수 크기의 행렬이 나온다
* 행렬의 곱셈은 교환법칙이 성립하지 않는다. 대신 결합법칙은 성립한다. 따라서 분배법칙도 가능하다

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

3x2 행렬 B>>
[[1 1]
 [2 2]
 [3 3]]


In [13]:
a_dot_b = a @ b
b_dot_a = b @ a
print('AB>>\n{}\n'.format(a_dot_b))
print('BA>>\n{}'.format(b_dot_a))

AB>>
[[14 14]
 [32 32]]

BA>>
[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}\n'.format(b.shape[0], b.shape[1], b))
print('{}x{} 행렬 C>>\n{}'.format(c.shape[0], c.shape[1], c))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[ 7  8  9]
 [10 11 12]]

3x2 행렬 C>>
[[1 1]
 [2 2]
 [3 3]]


In [15]:
a_dot_c_add_b_dot_c = (a @ c) + (b @ c)
a_add_b_dot_c = (a + b) @ c
print('AC + BC>>\n{}\n'.format(a_dot_c_add_b_dot_c))
print('(A + B)C>>\n{}'.format(a_add_b_dot_c))

AC + BC>>
[[ 64  64]
 [100 100]]

(A + B)C>>
[[ 64  64]
 [100 100]]


### 행렬의 곱셈 = 함수의 합성

<img src="./figure/행렬 곱셈 합성.png"/>