<center><h1>1강 행렬과 행렬식</h1></center>
<hr>

## Table of Contents <a id="top"></a>

1. [행렬](#1)
    1. [용어정리](#1.1)
    2. [행렬의 연산](#1.2)
2. [연립일차방정식](#2)
    1. [행렬의 표현](#2.1)
    2. [가우스 조던 소거법](#2.2)
    3. [역행렬 이용](#2.3)
3. [행렬식](#3)
    1. [행렬식이란?](#3.1)
    2. [역행렬](#3.2)
    3. [크래머 공식](#3.3)

A. [연습문제](#A)

<hr>

In [1]:
import numpy as np

# 1. 행렬 <a id="1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 1.1. 용어정리 <a id="1.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 구성

* 성분(component): 행렬 안에 배열된 구성원
* 행(row): 행렬의 가로줄
* 열(column): 행렬의 세로줄
* mxn 행렬: m 행과 n 열로 이루어진 행렬

<img src="./figure/행렬 용어 정리.png"/>

### 주요 행렬

* 대각 행렬(Diagonal Matrix): 대각성분(Diagonal Component)를 제외한 나머지 성분이 0인 행렬.
* 영행렬(Zero Matrix): 모든 성분이 0인 행렬
* 전치 행렬(Transpose Matrix): 주대각선을 기준으로 뒤집은 행렬. a(i, j)가 a(j, i)로 변한다.
* 대칭 행렬(Symmetric Matrix): 행렬 A와 전치 행렬 AT가 같은 행렬 A
* 정사각 행렬(Square Matrix): 행과 열의 개수가 같은 행렬
* 단위 행렬(Identity Matrix): 모든 대각성분이 1이고 나머지 성분은 0인 정사각 행렬

In [2]:
diagonal_matrix = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0]])
print('대각 행렬>>\n{}'.format(diagonal_matrix))

대각 행렬>>
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [3]:
zero_matrix = np.zeros((3, 2), dtype=int)
print('대각 행렬>>\n{}'.format(zero_matrix))

대각 행렬>>
[[0 0]
 [0 0]
 [0 0]]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_transpose = a.T
print('원래 행렬>>\n{}\n'.format(a))
print('전치 행렬>>\n{}'.format(a_transpose))

원래 행렬>>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

전치 행렬>>
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [5]:
symmetric_matrix = np.array([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print('대칭 행렬>>\n{}\n'.format(symmetric_matrix))
print('전치된 대칭 행렬>>\n{}'.format(symmetric_matrix.T))

대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]

전치된 대칭 행렬>>
[[1 2 3]
 [2 2 4]
 [3 4 5]]


In [6]:
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('정사각 행렬>>\n{}'.format(square_matrix))

정사각 행렬>>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
identity_matrix_2x2 = np.eye(2, dtype=int)
print('2x2 단위 행렬>>\n{}\n'.format(identity_matrix_2x2))

identity_matrix_3x3 = np.eye(3, dtype=int)
print('3x3 단위 행렬>>\n{}'.format(identity_matrix_3x3))

2x2 단위 행렬>>
[[1 0]
 [0 1]]

3x3 단위 행렬>>
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 1.2. 행렬의 연산 <a id="1.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬의 덧셈, 뺄셈, 상수배

* 덧셈, 뺄셈, 상수배 연산은 같은 위치에 행렬의 성분끼리 연산한다.
* 덧셈에 대해서는 교환법칙(A + B = B + A)와 결합법칙(A + (B + C) = (A + B) + C) 모두 성립한다

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[1 1 1]
 [2 2 2]]


In [9]:
a_add_b = a + b
b_add_a = b + a
print('A + B>>\n{}\n'.format(a_add_b))
print('B + A>>\n{}'.format(b_add_a))

A + B>>
[[2 3 4]
 [6 7 8]]

B + A>>
[[2 3 4]
 [6 7 8]]


In [10]:
a_sub_b = a - b
b_sub_a = b - a
print('A - B>>\n{}\n'.format(a_sub_b))
print('B - A>>\n{}'.format(b_sub_a))

A - B>>
[[0 1 2]
 [2 3 4]]

B - A>>
[[ 0 -1 -2]
 [-2 -3 -4]]


In [11]:
scalar = 3
a_increase_c = a * scalar
c_increase_a = scalar * a
print('A x {}>>\n{}\n'.format(scalar, a_increase_c))
print('{} x A>>\n{}'.format(scalar, c_increase_a))

A x 3>>
[[ 3  6  9]
 [12 15 18]]

3 x A>>
[[ 3  6  9]
 [12 15 18]]


### 행렬의 곱셈

* 행렬의 곱셈 AB를 위해서는 A의 열의 개수와 B의 행의 개수가 같아야한다. 연산의 결과로 A의 행의 개수 x B의 열의 개수 크기의 행렬이 나온다
* 행렬의 곱셈은 교환법칙이 성립하지 않는다. 대신 결합법칙은 성립한다. 따라서 분배법칙도 가능하다

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}'.format(b.shape[0], b.shape[1], b))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

3x2 행렬 B>>
[[1 1]
 [2 2]
 [3 3]]


In [13]:
a_dot_b = a @ b
b_dot_a = b @ a
print('AB>>\n{}\n'.format(a_dot_b))
print('BA>>\n{}'.format(b_dot_a))

AB>>
[[14 14]
 [32 32]]

BA>>
[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[1, 1], [2, 2], [3, 3]])
print('{}x{} 행렬 A>>\n{}\n'.format(a.shape[0], a.shape[1], a))
print('{}x{} 행렬 B>>\n{}\n'.format(b.shape[0], b.shape[1], b))
print('{}x{} 행렬 C>>\n{}'.format(c.shape[0], c.shape[1], c))

2x3 행렬 A>>
[[1 2 3]
 [4 5 6]]

2x3 행렬 B>>
[[ 7  8  9]
 [10 11 12]]

3x2 행렬 C>>
[[1 1]
 [2 2]
 [3 3]]


In [15]:
a_dot_c_add_b_dot_c = (a @ c) + (b @ c)
a_add_b_dot_c = (a + b) @ c
print('AC + BC>>\n{}\n'.format(a_dot_c_add_b_dot_c))
print('(A + B)C>>\n{}'.format(a_add_b_dot_c))

AC + BC>>
[[ 64  64]
 [100 100]]

(A + B)C>>
[[ 64  64]
 [100 100]]


### 행렬의 곱셈 = 함수의 합성

<img src="./figure/행렬 곱셈 합성.png"/>

# 2. 연립일차방정식 <a id="2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 2.1. 행렬의 표현 <a id="2.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬과 연립일차방정식

* 행렬은 연립일차방정식의 해를 구하기 위해서 등장
* 연립일차방정식의 해를 구하는데 있어서 행렬을 사용하는 방법으로 (1) <b>가우스 조던 방법</b>과 (2) <b>역행렬</b>이 있다


<img src="./figure/연립일차방정식 표현.png"/>

## 2.2. 가우스 조던 소거법 <a id="2.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 가우스 조던 소거법

* 세 가지 기본행 연산을 사용해서 첨가행렬을 기약 행 사다리꼴로 변환하여 해를 구한다
    1. 한 행을 상수배한다
    2. 한 행을 상수배하여서 다른 행에 더한다
    3. 두 행을 맞바꾼다
* 가우스 소거법은 행 사다리꼴로 변환하는 과정을, 가우스 조던 소거법은 기약 행 사다리꼴로 변환하는 과정을 의미한다.
    * 행 사다리꼴은 각 행의 가장 왼쪽 1을 기준으로 다음 행의 값이 모두 0인 사다리꼴 형태
    * 기약 행 사다리꼴은 각 행의 가장 왼쪽 1을 기준으로 이전과 다음 행의 값이 모두 0인 사다리꼴 형태
* 가우스 소거법으로 해를 구하는 경우 상수해(해가 1개), 부정(해가 여러개, 일반해), 불능(해가 없음)이 나올 수 있다
* 가우스 조던 소거법은 효율적인 알고리즘은 아니지만 프로그래밍으로 알고리즘화 할 수 있으며 나아가 다양한 수학 원리의 기본이라는 점에서 중요하다

<img src="./figure/가우스 조던 소거법.png"/>

In [16]:
def swap(mat, i, j):
    mat[[i, j]] = mat[[j, i]]

In [17]:
def gauss_jordan(mat, jordan=True):
    n_row = mat.shape[0]
    n_col = mat.shape[1]
    
    row = 0
    col = 0 # index of col, which must be non-zero

    # 가우스 소거법
    while row < n_row:
        # 만약 행의 시작이 0이고 다음 행의 시작이 0이 아닌 r를 찾아서 swap.
        if mat[row, col] == 0:
            r = row + 1
            while r < n_row and mat[r, col] == 0:
                r += 1
            if r < n_row:
                swap(mat, row, r)
            else:
                col += 1
                if col == n_col:
                    row += 1
                    col = n_col - 1
        else:
            # 0이 아닌 값을 찾자!!!
            value = mat[row, col]
            if col + 1 < n_col and value == 0:
                col += 1
                value = mat[row, col]
            
            # 혹시 0으로 나누는 문제를 대비해서...
            if value != 0:
                mat[row] = mat[row] / value
            
            # -0이 보기 싫으니깐. 0으로 통일하자
            mat[row, :col] = 0
            
            # 현재 행의 시작은 1로 설정되었다. 이제부터 다음 행에서는 모두 값이 0이 되도록 소거한다
            for idx in range(row + 1, n_row):
                mat[idx] = mat[idx] - mat[row] * (mat[idx, col] / mat[row, col])
                
            
            row += 1
            col += 1
    
    # 조단 소거법
    if jordan:
        row = n_row - 1
        col = n_col - 2
        
        while row > 0:
            # 만약 현재 col이 0이라면 그건 해당 row가 모두 0이라는 것
            if mat[row, col] == 0:
                row -= 1
                continue

            # 만약 col이 1이 아니라면 일단 이전으로 이동한다. 가우스 조단 소거법에 의해서 일다 1로 시작해야한다.
            if col - 1 > 0 and mat[row, col] != 1:
                col -= 1

            # 1로 시작하는 경우에 대해서 소거법으로 위의 행들을 처리한다
            for idx in range(0, row):
                mat[idx] = mat[idx] - mat[row] * mat[idx, col]
            
            row -= 1
            col -= 1

In [18]:
original = np.array([[1, 2, 5], [2, 3, 8]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[1. 2. 5.]
 [2. 3. 8.]]

가우스 소거법 행렬 >>
[[1. 2. 5.]
 [0. 1. 2.]]

가우스 조던 소거법 행렬 >>
[[1. 0. 1.]
 [0. 1. 2.]]


In [19]:
original = np.array([[2, 4, -3, 1], [1, 1, 2, 9], [3, 6, -5, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))


원 행렬 >>
[[ 2.  4. -3.  1.]
 [ 1.  1.  2.  9.]
 [ 3.  6. -5.  0.]]

가우스 소거법 행렬 >>
[[ 1.   2.  -1.5  0.5]
 [ 0.   1.  -3.5 -8.5]
 [ 0.   0.   1.   3. ]]

가우스 조던 소거법 행렬 >>
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]]


In [20]:
original = np.array([[1, -1, 2, 5], [2, -3, 1, -10], [3, -3, 6, 15]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[  1.  -1.   2.   5.]
 [  2.  -3.   1. -10.]
 [  3.  -3.   6.  15.]]

가우스 소거법 행렬 >>
[[ 1. -1.  2.  5.]
 [ 0.  1.  3. 20.]
 [ 0.  0.  0.  0.]]

가우스 조던 소거법 행렬 >>
[[ 1.  0.  5. 25.]
 [ 0.  1.  3. 20.]
 [ 0.  0.  0.  0.]]


In [21]:
original = np.array([[2, 4, -2, 6], [1, 1, 2, 9], [1, 2, -1, 4]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 2.  4. -2.  6.]
 [ 1.  1.  2.  9.]
 [ 1.  2. -1.  4.]]

가우스 소거법 행렬 >>
[[ 1.  2. -1.  3.]
 [ 0.  1. -3. -6.]
 [ 0.  0.  0.  1.]]

가우스 조던 소거법 행렬 >>
[[ 1.  0.  5. 15.]
 [ 0.  1. -3. -6.]
 [ 0.  0.  0.  1.]]


In [22]:
original = np.array([[1, 1, 2, 4, 1, 0], [0, 0, 1, 1, 2, 0], [2, 2, -1, 3, 0, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 1.  1.  2.  4.  1.  0.]
 [ 0.  0.  1.  1.  2.  0.]
 [ 2.  2. -1.  3.  0.  0.]]

가우스 소거법 행렬 >>
[[1. 1. 2. 4. 1. 0.]
 [0. 0. 1. 1. 2. 0.]
 [0. 0. 0. 0. 1. 0.]]

가우스 조던 소거법 행렬 >>
[[ 1.  1. -2.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]]


## 2.3. 역행렬 이용<a id="2.3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 역행렬을 이용한 연립일차방정식 해 구하기

* AX = B에 대해서 행렬 A의 역행렬이 존재할 때 X = A(-1)B이다.
* 역행렬의 존재를 어떻게 판별할지, 그리고 역행렬을 어떻게 구할지가 중요 -> 행렬식

# 3. 행렬식 <a id="3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

## 3.1. 행렬식이란? <a id="3.1"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬식(Determinant)

* 행렬식은 정사각 행렬(Square Matrix)를 하나의 수로 대응시키는 특별한 함수를 의미한다.

<img src="./figure/행렬식 공식.png"></img>

* 3x3에서 a11, a12, a13에 대해서 계산하였지만, 같은 행 또는 같은 열의 성분들은 행렬식 계산에 사용할 수 있다.
* 이 때 부호를 주의해야한다.

<img src="./figure/3차 행렬식 구하기.png"/>

### 사루스 법칙(전개) - 3차 행렬식을 빠르게 구하기

* 3차 행렬식을 빠르게 구하기 위한 방법
* 1열과 2열의 값을 행렬 A 오른쪽으로 쌓는다.
* 3차 행렬식은 하향하는 대각선 방향의 성분 곱의 합과 상향하는 대각선 방향의 성분 곱의 합의 차이다

<img src="./figure/사루스 전개.png"/>

In [23]:
def minor_matrix(matrix, i, j):
    minor_matrix = matrix.copy()
    minor_matrix = np.delete(minor_matrix, [i], axis=0)
    minor_matrix = np.delete(minor_matrix, [j], axis=1)
    return minor_matrix

In [24]:
def calculate_determinant(square_matrix, n):
    if n == 0:
        return 0
    if n == 1:
        return square_matrix[0][0]
    
    det = 0.
    for idx in range(n):
        minor_mat = minor_matrix(square_matrix, 0, idx)
        det += (((-1) ** (idx)) * square_matrix[0, idx]) * calculate_determinant(minor_mat, n - 1)
    
    return det

In [25]:
a = np.array([[1, 2, 3], [0, 1, 0], [1, 2, 0]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[1 2 3]
 [0 1 0]
 [1 2 0]]

행렬식 det(A)의 값은 -3.0


In [26]:
a = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[1 2 3]
 [2 5 3]
 [1 0 8]]

행렬식 det(A)의 값은 -1.0


In [27]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 2  4 -3]
 [ 1  1  2]
 [ 3  6 -5]]

행렬식 det(A)의 값은 1.0


In [28]:
a = np.array([[1, -1, 2], [2, -3, 1], [3, -3, 6]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 1 -1  2]
 [ 2 -3  1]
 [ 3 -3  6]]

행렬식 det(A)의 값은 0.0


In [29]:
a = np.array([[2, 4, -2], [1, 1, 2], [1, 2, -1]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

3차 행렬 A >> 
[[ 2  4 -2]
 [ 1  1  2]
 [ 1  2 -1]]

행렬식 det(A)의 값은 0.0


In [30]:
a = np.array([[1, 1, 2, 4, 1], [0, 0, 1, 1, 2], [2, 2, -1, 3, 0,], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])
print('{}차 행렬 A >> \n{}\n'.format(a.shape[0], a))

det_a = calculate_determinant(a, a.shape[0])
print('행렬식 det(A)의 값은 {}'.format(det_a))

5차 행렬 A >> 
[[ 1  1  2  4  1]
 [ 0  0  1  1  2]
 [ 2  2 -1  3  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

행렬식 det(A)의 값은 0.0


## 3.2. 역행렬 <a id="3.2"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 행렬식과 역행렬

* 행렬 A에 대해서 행렬식 det(A)가 0이면 행렬 A에 대해서 역행렬이 존재하지 않는다. -> 연립일차방정식의 해는 부정 또는 불능
* 행렬 A에 대해서 행렬식 det(A)가 0이 아니면 역행렬 A(-1)는 행렬식과 Minor Matrix의 행렬식을 사용해서 표현한다

<img src="./figure/역행렬 구하기.png"/>

In [31]:
def adjoint_matrix(matrix):
    adj_matrix = np.zeros_like(matrix, dtype=float)
    
    n = matrix.shape[0]
    
    for row in range(n):
        for col in range(n):
            m = minor_matrix(matrix, row, col)
            adj_matrix[col, row] = ((-1) ** (row + col)) * calculate_determinant(m, m.shape[0])
    
    return adj_matrix
    

In [32]:
def calculate_inverse_matrix(matrix):
    det = calculate_determinant(matrix, matrix.shape[0])
    if det != 0:
        adj_matrix = adjoint_matrix(matrix)
        adj_matrix /= det
        return True, adj_matrix
    
    return False, matrix

In [33]:
a = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


In [34]:
a = np.array([[2, 1], [4, 3]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[ 1.5 -0.5]
 [-2.   1. ]]


In [35]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
p, a_inv = calculate_inverse_matrix(a)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}'.format(a_inv))

역행렬을 구할 수 있습니다
결과값 >>
[[-17.   2.  11.]
 [ 11.  -1.  -7.]
 [  3.  -0.  -2.]]


In [36]:
a_inv @ np.array([1, 9, 0])

array([1., 2., 3.])

## 3.3. 크래머 공식 <a id="3.3"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

### 크래머 공식

* 연립일차방정식의 모든 미지수(x, y, z, ...)를 역행렬을 통해 계산하는 긋은 많은 계산량이 필요하다
* 크래머 공식은 특정한 미지수(x)에 대해서만 그 해를 구할 때 사용하는 방법으로 행렬식을 활용한다

<img src="./figure/크래머 공식.png"/>

In [37]:
def cramer_matrix(matrix, k, constant):
    cramer = matrix.copy()
    cramer[:, k] = constant
    return cramer

In [38]:
def cramer_rule(matrix, constant):
    n = matrix.shape[0]
    variables = list()
    for variable in range(n):
        det_a = calculate_determinant(matrix, matrix.shape[0])
        
        ak = cramer_matrix(matrix, variable, constant)
        det_ak = calculate_determinant(ak, ak.shape[0])
        
        variables.append(det_ak / det_a)
    
    return np.array(variables)

In [39]:
a = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]])
constant = np.array([1, 9, 0])
print('연립일차방정식을 행렬로 표현한 A >>\n{}\n'.format(a))
print('연립일차방정식의 상수 >> {}\n'.format(constant))
variables = cramer_rule(a, constant)
print('연립일차장정식의 해 >> {}\n'.format(variables))

연립일차방정식을 행렬로 표현한 A >>
[[ 2  4 -3]
 [ 1  1  2]
 [ 3  6 -5]]

연립일차방정식의 상수 >> [1 9 0]

연립일차장정식의 해 >> [1. 2. 3.]



In [40]:
a = np.array([[1, 0, 2], [-1, -2, 3], [-3, 4, 6]])
constant = np.array([6, 8, 30])
print('연립일차방정식을 행렬로 표현한 A >>\n{}\n'.format(a))
print('연립일차방정식의 상수 >> {}\n'.format(constant))
variables = cramer_rule(a, constant)
print('연립일차장정식의 해 >> {}\n'.format(variables))

연립일차방정식을 행렬로 표현한 A >>
[[ 1  0  2]
 [-1 -2  3]
 [-3  4  6]]

연립일차방정식의 상수 >> [ 6  8 30]

연립일차장정식의 해 >> [-0.90909091  1.63636364  3.45454545]



<hr>

## 연습문제 <a id="A"></a>
<p style="text-align:right;"><a href="#top">🔝 top</a></p>

**1. 연립일차방정식을 가우스 조건 소거법 또는 역행렬을 이용하여서 풀이하고, 해에 대해 탐구하시오.**

**1)<br>
2x + 4y - 3z = 1 <br>
x + y + 2z = 9 <br>
3x + 6y - 5z = 0 <br>
<br>
answer: x = 1, y = 2, z = 3**

In [41]:
original = np.array([[2, 4, -3, 1], [1, 1, 2, 9], [3, 6, -5, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 2.  4. -3.  1.]
 [ 1.  1.  2.  9.]
 [ 3.  6. -5.  0.]]

가우스 소거법 행렬 >>
[[ 1.   2.  -1.5  0.5]
 [ 0.   1.  -3.5 -8.5]
 [ 0.   0.   1.   3. ]]

가우스 조던 소거법 행렬 >>
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]]


In [42]:
original = np.array([[2, 4, -3], [1, 1, 2], [3, 6, -5]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

if p:
    constant = np.array([[1], [9], [0]], dtype=float)
    variables = original_inv @ constant
    print('연립일차방정식의 해 >>\n{}'.format(variables))

원 행렬 >>
[[ 2.  4. -3.]
 [ 1.  1.  2.]
 [ 3.  6. -5.]]

역행렬을 구할 수 있습니다
결과값 >>
[[-17.   2.  11.]
 [ 11.  -1.  -7.]
 [  3.  -0.  -2.]]

연립일차방정식의 해 >>
[[1.]
 [2.]
 [3.]]


**<br>2)<br>
x - y + 2z = 5 <br>
2x - 3y + z = -10 <br>
3x - 3y + 6z = 15 <br>
<br>
answer: x = 25 - 5z, y = 20 - 3z, z = t**

In [43]:
original = np.array([[1, -1, 2, 5], [2, -3, 1, -10], [3, -3, 6, 15]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[  1.  -1.   2.   5.]
 [  2.  -3.   1. -10.]
 [  3.  -3.   6.  15.]]

가우스 소거법 행렬 >>
[[ 1. -1.  2.  5.]
 [ 0.  1.  3. 20.]
 [ 0.  0.  0.  0.]]

가우스 조던 소거법 행렬 >>
[[ 1.  0.  5. 25.]
 [ 0.  1.  3. 20.]
 [ 0.  0.  0.  0.]]


In [44]:
original = np.array([[1, -1, 2], [2, -3, 1], [3, -3, 6]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

if p:
    constant = np.array([[5], [-10], [15]], dtype=float)
    variables = original_inv @ constant
    print('연립일차방정식의 해 >>\n{}'.format(variables))

원 행렬 >>
[[ 1. -1.  2.]
 [ 2. -3.  1.]
 [ 3. -3.  6.]]

역행렬을 구할 수 없습니다
결과값 >>
[[ 1. -1.  2.]
 [ 2. -3.  1.]
 [ 3. -3.  6.]]



**<br>3)<br>
2x + 4y - 2z = 6 <br>
x + y + 2z = 9 <br>
x + 2y - z = 4 <br>
<br>
answer: 불능**

In [45]:
original = np.array([[2, 4, -2, 6], [1, 1, 2, 9], [1, 2, -1, 4]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 2.  4. -2.  6.]
 [ 1.  1.  2.  9.]
 [ 1.  2. -1.  4.]]

가우스 소거법 행렬 >>
[[ 1.  2. -1.  3.]
 [ 0.  1. -3. -6.]
 [ 0.  0.  0.  1.]]

가우스 조던 소거법 행렬 >>
[[ 1.  0.  5. 15.]
 [ 0.  1. -3. -6.]
 [ 0.  0.  0.  1.]]


In [46]:
original = np.array([[2, 4, -2], [1, 1, 2], [1, 2, -1]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

if p:
    constant = np.array([[6], [9], [4]], dtype=float)
    variables = original_inv @ constant
    print('연립일차방정식의 해 >>\n{}'.format(variables))

원 행렬 >>
[[ 2.  4. -2.]
 [ 1.  1.  2.]
 [ 1.  2. -1.]]

역행렬을 구할 수 없습니다
결과값 >>
[[ 2.  4. -2.]
 [ 1.  1.  2.]
 [ 1.  2. -1.]]



**<br>4)<br>
x + y + 2z + 4w + v = 0 <br>
z + w + 2v = 0 <br>
2x + 2y - z + 3w = 0 <br>
<br>
answer: x = -s - 2t, y = s, z = -t, w = t, v = 0**

In [47]:
original = np.array([[1, 1, 2, 4, 1, 0], [0, 0, 1, 1, 2, 0], [2, 2, -1, 3, 0, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

gauss_mat = original.copy()
gauss_jordan(gauss_mat, jordan=False)
print('가우스 소거법 행렬 >>\n{}\n'.format(gauss_mat))

gauss_jordan_mat = original.copy()
gauss_jordan(gauss_jordan_mat, jordan=True)
print('가우스 조던 소거법 행렬 >>\n{}'.format(gauss_jordan_mat))

원 행렬 >>
[[ 1.  1.  2.  4.  1.  0.]
 [ 0.  0.  1.  1.  2.  0.]
 [ 2.  2. -1.  3.  0.  0.]]

가우스 소거법 행렬 >>
[[1. 1. 2. 4. 1. 0.]
 [0. 0. 1. 1. 2. 0.]
 [0. 0. 0. 0. 1. 0.]]

가우스 조던 소거법 행렬 >>
[[ 1.  1. -2.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]]


In [48]:
original = np.array([[1, 1, 2, 4, 1], [0, 0, 1, 1, 2], [2, 2, -1, 3, 0]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

if p:
    constant = np.array([[6], [9], [4]], dtype=float)
    variables = original_inv @ constant
    print('연립일차방정식의 해 >>\n{}'.format(variables))

원 행렬 >>
[[ 1.  1.  2.  4.  1.]
 [ 0.  0.  1.  1.  2.]
 [ 2.  2. -1.  3.  0.]]

역행렬을 구할 수 없습니다
결과값 >>
[[ 1.  1.  2.  4.  1.]
 [ 0.  0.  1.  1.  2.]
 [ 2.  2. -1.  3.  0.]]



**<br>2. 역행렬이 존재하는 두 정사각행렬 A, B에 대하여 (AB)-1 = B-1A-1임을 보이시오**

ABX = I<br>
BX = A-1<br>
X = B-1A-1<br>


**<br>3. 다음 행렬의 역행렬을 구하시오.**

**1)<br>
(2, 1)<br>
(4, 3)<br>
<br>
answer: <br>
(1.5, -0.5)<br>
(-2, 1)<br>**

In [49]:
original = np.array([[2, 1], [4, 3]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

원 행렬 >>
[[2. 1.]
 [4. 3.]]

역행렬을 구할 수 있습니다
결과값 >>
[[ 1.5 -0.5]
 [-2.   1. ]]



**2)<br>
(1, 2, 3)<br>
(2, 5, 3)<br>
(1, 0, 8)<br>
<br>
answer: <br>
(-40, 16, 9)<br>
(13, -5, -3)<br>
(5, -2, -1)<br>
<br>**

In [50]:
original = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]], dtype=float)
print('원 행렬 >>\n{}\n'.format(original))

p, original_inv = calculate_inverse_matrix(original)
print('역행렬을 구할 수 {}'.format('있습니다' if p else '없습니다'))
print('결과값 >>\n{}\n'.format(original_inv))

원 행렬 >>
[[1. 2. 3.]
 [2. 5. 3.]
 [1. 0. 8.]]

역행렬을 구할 수 있습니다
결과값 >>
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]



**4. 정사각행렬 A와 A의 역행렬 A-1에 대하여 det(A-1) = 1/det(A) 임을 증명하시오.**

해당 문제를 증명하기 위해서 다음과 같은 명제를 받아들일 필요가 있다.<br>
1. 가역인 모든 행렬은 기본행렬의 곱으로 표현할 수 있다.<br>
2. 임의의 정사각행렬 A에 대해서 det(AE) = det(A) det(E) 이다.<br>

<img src="./figure/가역행렬은 기본행렬의 곱.png"/>

<img src="./figure/기본행렬의 판별식.png"/>

다음 사항을 받아들인다면 문제에서 제시한 역행렬의 판별식은 원래 행렬의 판별식의 역수임을 증명할 수 있다.

<img src="./figure/증명.png"/>

**5. 크래머 공식을 이용하여 다음 연립일차방정식의 해를 구하시오.**

**1)<br>
5x + 3y + 2 = 0<br>
4x - y + 5 = 0<br>
<br>
answer: x = -1, y = 1**

In [51]:
a = np.array([[5, 3], [4, -1]])
constant = np.array([-2, -5])
print('연립일차방정식을 행렬로 표현한 A >>\n{}\n'.format(a))
print('연립일차방정식의 상수 >> {}\n'.format(constant))
variables = cramer_rule(a, constant)
print('연립일차장정식의 해 >> {}\n'.format(variables))

연립일차방정식을 행렬로 표현한 A >>
[[ 5  3]
 [ 4 -1]]

연립일차방정식의 상수 >> [-2 -5]

연립일차장정식의 해 >> [-1.  1.]



**2)<br>
x + 2z = 6<br>
-x - 2y + 3z = 8<br>
-3x + 4y + 6z = 30<br>
<br>
answer: x = -90909090, y = 1.6363636363, z = 3.4545454545**

In [52]:
a = np.array([[1, 0, 2], [-1, -2, 3], [-3, 4, 6]])
constant = np.array([6, 8, 30])
print('연립일차방정식을 행렬로 표현한 A >>\n{}\n'.format(a))
print('연립일차방정식의 상수 >> {}\n'.format(constant))
variables = cramer_rule(a, constant)
print('연립일차장정식의 해 >> {}\n'.format(variables))

연립일차방정식을 행렬로 표현한 A >>
[[ 1  0  2]
 [-1 -2  3]
 [-3  4  6]]

연립일차방정식의 상수 >> [ 6  8 30]

연립일차장정식의 해 >> [-0.90909091  1.63636364  3.45454545]

